version: "3"

services:
  dtrack:
    image: dependencytrack/bundled:4.5.0@sha256:eb8d446d41a03bae46aa9a68692de08ba62946994563287c100d245471a09812
    ports:
    - "127.0.0.1:8080:8080"
    restart: unless-stopped

  dtapac:
    build: ../../../
    environment:
      DTRACK_URL: "http://dtrack:8080"
      DTRACK_APIKEY: "changeme"
      OPA_URL: "http://opa:8181"
      FINDING_POLICY_PATH: "/dtapac/finding"
      VIOLATION_POLICY_PATH: "/dtapac/violation"
      PORTFOLIO_ANALYSIS_INTERVAL: "1m"
      LOG_LEVEL: "debug"
    ports:
    - "127.0.0.1:8081:8080"
    restart: unless-stopped

  opa:
    image: openpolicyagent/opa:0.41.0-rootless@sha256:530cbe6d3e3f99966aba8563e5c4a63e4f89ff70ece959b57fd617fa0dca70b6
    command:
    - run
    - --server
    - --log-format=json-pretty
    - --set=decision_logs.console=true
    - --set=status.console=true
    - --watch
    - /opt/dtapac/policies
    ports:
    - "127.0.0.1:8181:8181"
    volumes:
    - "../../policies:/opt/dtapac/policies"
    restart: unless-stopped
