version: "3"

services:
  dtapac:
    build: .
    depends_on:
    - dtrack
    - opa
    environment:
      DTAPAC_DTRACK_URL: "http://dtrack:8080"
      DTAPAC_DTRACK_APIKEY: "${DTAPAC_DTRACK_APIKEY}"
      DTAPAC_OPA_URL: "http://opa:8181"
      DTAPAC_OPA_BUNDLE: "dtapac"
      DTAPAC_POLICY_PATH: "/v1/data/dtapac/finding/analysis"
      DTAPAC_LOG_LEVEL: "debug"
    networks:
    - public
    ports:
    - "127.0.0.1:8081:8080"
    restart: unless-stopped

  dtrack:
    image: dependencytrack/bundled:4.4.2
    networks:
    - public
    ports:
    - "127.0.0.1:8080:8080"
    restart: unless-stopped

  opa:
    image: openpolicyagent/opa:0.39.0-rootless
    command:
    - run
    - --server
    # (Periodically) pull mybundle from NGINX
    - --set=services.bundle_server.url=http://opa_bundle_server
    - --set=bundles.dtapac.service=bundle_server
    - --set=bundles.dtapac.resource=bundles/dtapac.tar.gz
    # Send status notifications to DTAPAC
    - --set=services.dtapac.url=http://dtapac:8080/opa
    - --set=status.service=dtapac
    depends_on:
    - opa_bundle_server
    networks:
    - opa_internal
    - public
    ports:
    - "127.0.0.1:8181:8181"
    restart: unless-stopped

  opa_bundle_server:
    image: nginx:1.21.6-alpine
    networks:
    - opa_internal
    volumes:
    - "./examples/bundles:/usr/share/nginx/html/bundles:ro"
    restart: unless-stopped

networks:
  public: {}
  opa_internal:
    internal: true