name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed to push images

jobs:
  release:
    name: Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.18"
        check-latest: true
    - name: Set up cyclonedx-gomod
      uses: CycloneDX/gh-gomod-generate-sbom@v1.1.0
      with:
        version: v1
    - name: Set up cosign
      uses: sigstore/cosign-installer@v2.4.0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3.0.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
